config = {}

config.itemList = {
	{ ['item'] = 'cellphone', ['damageItem'] = 'cellphonedamaged' },
	{ ['item'] = 'nbcellphone', ['damageItem'] = 'cellphonedamaged' },
	{ ['item'] = 'radio', ['damageItem'] = 'radiodamaged' },
	{ ['item'] = 'dollars', ['damageItem'] = '' },
	{ ['item'] = 'dollars2', ['damageItem'] = '' },
	{ ['item'] = 'identity', ['damageItem'] = '' },
	{ ['item'] = 'battery', ['damageItem'] = '' },
	{ ['item'] = 'alface', ['damageItem'] = '' },
	{ ['item'] = 'bacon', ['damageItem'] = '' },
	{ ['item'] = 'bread', ['damageItem'] = '' },
	{ ['item'] = 'burguer', ['damageItem'] = '' },
	{ ['item'] = 'onion', ['damageItem'] = '' },
	{ ['item'] = 'presunto', ['damageItem'] = '' },
	{ ['item'] = 'queijo', ['damageItem'] = '' },
	{ ['item'] = 'tomate', ['damageItem'] = '' },
	{ ['item'] = 'coffee', ['damageItem'] = '' },
	{ ['item'] = 'badcoffee', ['damageItem'] = '' },
	{ ['item'] = 'hamburger', ['damageItem'] = '' },
	{ ['item'] = 'badhamburger', ['damageItem'] = '' },
	{ ['item'] = 'chocolate', ['damageItem'] = '' },
	{ ['item'] = 'badchocolate', ['damageItem'] = '' },
	{ ['item'] = 'donut', ['damageItem'] = '' },
	{ ['item'] = 'baddonut', ['damageItem'] = '' },
	{ ['item'] = 'postit', ['damageItem'] = '' },
	{ ['item'] = 'hood', ['damageItem'] = '' },
	{ ['item'] = 'c4', ['damageItem'] = '' }
}